### PR TITLE
Add gasUsage topic

### PR DESCRIPTION
**Pull request by zegerk**
Added the gasUsage, which is a bit different from electricity usage since the value is updated based on usage (0.0XX m3) and not the "actual" usage. Patched some code to avoid showing the gas meter value as usage when starting up - it messes up graphs

### CODE REVIEW

**Comment by svrooij** [comment]
Scrolling through the code makes me happy. Having gas usage makes this app just a little bit better! Also you are probably the first contributor next to myself.

Will accept this PR and release a new beta. Just to see if it doesn’t break my own setup.

**Comment by svrooij** [comment]
Or you still want to change things? Then I’ll just wait for a bit and merge it in one go.

**Comment by zeger-pon** [comment]
Always happy to contribute to open-source - think one more day of gas testing and this pull request is ready to go.

**Comment by zegerk** [comment]
Always happy to contribute to open-source - think one more day of gas testing and this pull request is ready to go.

**Comment by svrooij** [comment]
If you start at least one of the commit messages with `fix: some description` it will auto release your changes once I'll approve your PR.

**Comment by svrooij** [comment]
My gas meter only emits a new value for the gas usage every hour (60 min) exactly at the hour. So 12:00:00, 13:00:00, 14:00:00

**Comment by zegerk** [comment]
Ah, the latest meters have 5m timestamps - codewise It does not matter, updated comment

**Pull request merged**
